<?php

/**
 * Implements hook_preprocess().
 */
function brecht_preprocess(array &$variables, string $hook): void {
  if (str_contains($hook, 'image')) {
    $files = glob(realpath(\Drupal::service('extension.list.module')->getPath('brecht')) . '/images' . '/*.*');
    $file = array_rand($files);

    if (isset($variables['responsive_image']['#uri'])) {
      $variables['responsive_image']['#uri'] = 'module://brecht/images/' . basename($files[$file]);
    }

    if (isset($variables['image']['#uri'])) {
      $variables['image']['#uri'] = 'module://brecht/images/' . basename($files[$file]);
    }

    if (isset($variables['uri'])) {
      $variables['uri'] = '/modules/custom/brecht/images/' . basename($files[$file]);
    }
  }
}